apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: routemanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: routemanager
    spec:
      containers:
      - name: routemanager
        image: acrdenkers.azurecr.io/deliverymanagement.route-manager:1100
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 150m		
      imagePullSecrets:
      - name: keyacr
      
---
apiVersion: v1
kind: Service
metadata:
  name: routemanager
  labels:
    name: routemanager
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: routemanager
