apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: routemanagertest
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: routemanagertest
    spec:
      containers:
      - name: routemanagertest
        image: acrdenkers.azurecr.io/deliverymanagement.route-manager:1423
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev	
      imagePullSecrets:
      - name: keyacr
      
---
apiVersion: v1
kind: Service
metadata:
  name: routemanagertest
  labels:
    name: routemanagertest
spec:
  type: ClusterIP
  ports:
  - port: 30486
  selector:
    app: routemanagertest
